# Generated by Django 5.2 on 2025-04-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_options_alter_post_contend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contend',
            new_name='content',
        ),
    ]
